local _G = GLOBAL
local require = _G.require
local STRINGS = _G.STRINGS
--[[
-- 名称
STRINGS.NAMES.[物品名称] = ""
-- 建造栏描述
STRINGS.RECIPE_DESC.[物品名称] = ""

-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.[物品名称] = ""
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.[物品名称] = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.[物品名称] = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.[物品名称] = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.[物品名称] = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.[物品名称] = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.[物品名称] = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.[物品名称] = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.[物品名称] = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.[物品名称] = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.[物品名称] = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.[物品名称] = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.[物品名称] = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.[物品名称] = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.[物品名称] = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.[物品名称] = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.[物品名称] = ""
]]




-- 农场
STRINGS.NAMES.SUCCULENT_FARM = "多肉农场" -- 名称
STRINGS.RECIPE_DESC.SUCCULENT_FARM = "还有这种农场?" -- 建造栏描述
--------------------------------------------------------------------------
-- 农场状态
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FARM =
{
    -- 阶段4
    STUFFED = "如果不是花盆的限制它们可能会更多",
    -- 阶段3
    LOTS = "挤满了花盆",
    -- 阶段1\2
    SOME = "这是个好的趋势",
    -- 空
    EMPTY = "可以种点多肉",
    -- 烧毁
    BURNT = "大火带走了一切",
    -- 正常检查
    GENERIC = "种点多肉植物吧",
}
-- 满肥料
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.NONEEDFERTILIZE = "暂时不需要施肥"
-- 试图栽种不是多肉
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.MUSTBESUCCULENT = "这里面可种不了这个"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 大型多肉盆栽
STRINGS.NAMES.SUCCULENT_LARGEPOT = "大型多肉盆栽"
STRINGS.RECIPE_DESC.SUCCULENT_LARGEPOT = "失去了让植物生长的能力"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_LARGEPOT = "挺好看的嘛"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_LARGEPOT = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_LARGEPOT = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 盆栽
STRINGS.NAMES.SUCCULENT_MEDPOT = "肉肉盆栽"
STRINGS.RECIPE_DESC.SUCCULENT_MEDPOT = "大一点的多肉盆栽"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_MEDPOT = "它看起来比一般的大一点"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_MEDPOT = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_MEDPOT = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_MEDPOT = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------

--食物
STRINGS.NAMES.PPF_SUCCULENTJELLY = "平凡果冻"
STRINGS.UI.COOKBOOK.PPF_SUCCULENTJELLY = "给百分比最低的属性额外回复"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_SUCCULENTJELLY =
{
    --[[普通检查]]      GENERIC = "神奇的食物", --[[吃完恢复饥饿值]]    HUNGER = "肚子不是很饿了",
    --[[吃完恢复血量]]  HEALTH = "伤势好多了", --[[吃完恢复精神值]]     SANITY = "小脑袋瓜清醒了"
}
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_SUCCULENTJELLY =
{
    GENERIC = "", HUNGER = "",
    HEALTH = "", SANITY = ""
 }-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_SUCCULENTJELLY =
{
   GENERIC = "", HUNGER = "",
   HEALTH = "", SANITY = ""
}


STRINGS.NAMES.PPF_SUCCULENTJUICE = "祛炎饮料"    --祛炎
STRINGS.UI.COOKBOOK.PPF_SUCCULENTJUICE = "夏天不就应该喝点冰吗"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_SUCCULENTJUICE =
{
    --[[普通检查]]  GENERIC = "看起来很清爽",
    --[[降温]]      COOL = "好凉快!",
    --[[过冷]]      COLD = "哇, 太凉了!"
}
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_SUCCULENTJUICE =
{
    GENERIC = "",
    COOL = "",
    COLD = ""
}
--------------------------------------------------------------------------
--------------------------------------------------------------------------

STRINGS.NAMES.PPF_GREENTONGUE = "绿舌头"    --绿舌头
STRINGS.UI.COOKBOOK.PPF_GREENTONGUE = "放在冰箱不会融化"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_GREENTONGUE = "童年的味道!"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_GREENTONGUE = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_GREENTONGUE = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_GREENTONGUE = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_GREENTONGUE = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_GREENTONGUE = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_GREENTONGUE = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_GREENTONGUE = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_GREENTONGUE = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_GREENTONGUE = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_GREENTONGUE = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_GREENTONGUE = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------

STRINGS.NAMES.PPF_POMEGRANATE = "石榴汤"    --石榴汤
STRINGS.UI.COOKBOOK.PPF_POMEGRANATE = "石榴包裹着石头的力量"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_POMEGRANATE = "可不能把石头吞下去"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_POMEGRANATE = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_POMEGRANATE = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_POMEGRANATE = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_POMEGRANATE = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_POMEGRANATE = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_POMEGRANATE = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_POMEGRANATE = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_POMEGRANATE = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_POMEGRANATE = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_POMEGRANATE = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_POMEGRANATE = ""
--------------------------------------------------------------------------
-- 勿改 --
local stonefood ={wilson = STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_POMEGRANATE,willow = STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_POMEGRANATE,wolfgang = STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_POMEGRANATE,wendy = STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_POMEGRANATE,WX78 = STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_POMEGRANATE,wickerbottom = STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_POMEGRANATE,woodie = STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_POMEGRANATE,waxwell = STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_POMEGRANATE,wathgrithr = STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_POMEGRANATE,webber = STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_POMEGRANATE,winona = STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_POMEGRANATE,warly = STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_POMEGRANATE,wortox = STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_POMEGRANATE,wormwood = STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_POMEGRANATE,wurt = STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_POMEGRANATE,walter = STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_POMEGRANATE,wanda = STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_POMEGRANATE,}
STRINGS.NAMES.PPF_DURIAN = "榴莲汤"    --榴莲汤
STRINGS.UI.COOKBOOK.PPF_DURIAN = "榴莲包裹着石头的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_DURIAN = stonefood.wilson
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_DURIAN = stonefood.willow
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_DURIAN = stonefood.wolfgang
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_DURIAN = stonefood.wendy
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_DURIAN = stonefood.wx78
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_DURIAN = stonefood.wickerbottom
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_DURIAN = stonefood.woodie
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_DURIAN = stonefood.waxwell
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_DURIAN = stonefood.wathgrithr
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_DURIAN = stonefood.webber
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_DURIAN = stonefood.winona
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_DURIAN = stonefood.warly
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_DURIAN = stonefood.wortox
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_DURIAN = stonefood.wormwood
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_DURIAN = stonefood.wurt
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_DURIAN = stonefood.walter
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_DURIAN = stonefood.wanda
STRINGS.NAMES.PPF_WATERMELON = "西瓜汤"    --西瓜汤
STRINGS.UI.COOKBOOK.PPF_WATERMELON = "西瓜包裹着石头的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_WATERMELON = stonefood.wilson
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_WATERMELON = stonefood.willow
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_WATERMELON = stonefood.wolfgang
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_WATERMELON = stonefood.wendy
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_WATERMELON = stonefood.wx78
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_WATERMELON = stonefood.wickerbottom
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_WATERMELON = stonefood.woodie
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_WATERMELON = stonefood.waxwell
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_WATERMELON = stonefood.wathgrithr
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_WATERMELON = stonefood.webber
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_WATERMELON = stonefood.winona
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_WATERMELON = stonefood.warly
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_WATERMELON = stonefood.wortox
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_WATERMELON = stonefood.wormwood
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_WATERMELON = stonefood.wurt
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_WATERMELON = stonefood.walter
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_WATERMELON = stonefood.wanda
STRINGS.NAMES.PPF_DRAGONFRUIT = "火龙果汤"    --火龙果汤
STRINGS.UI.COOKBOOK.PPF_DRAGONFRUIT = "火龙果包裹着石头的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wilson
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_DRAGONFRUIT = stonefood.willow
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wolfgang
STRINGS.CHARACTERS.WENDY.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wendy
STRINGS.CHARACTERS.WX78.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wx78
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wickerbottom
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PPF_DRAGONFRUIT = stonefood.woodie
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PPF_DRAGONFRUIT = stonefood.waxwell
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wathgrithr
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_DRAGONFRUIT = stonefood.webber
STRINGS.CHARACTERS.WINONA.DESCRIBE.PPF_DRAGONFRUIT = stonefood.winona
STRINGS.CHARACTERS.WARLY.DESCRIBE.PPF_DRAGONFRUIT = stonefood.warly
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wortox
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wormwood
STRINGS.CHARACTERS.WURT.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wurt
STRINGS.CHARACTERS.WALTER.DESCRIBE.PPF_DRAGONFRUIT = stonefood.walter
STRINGS.CHARACTERS.WANDA.DESCRIBE.PPF_DRAGONFRUIT = stonefood.wanda
-- end --
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 玉露
STRINGS.NAMES.DEWDROP = "玉露"
STRINGS.UI.COOKBOOK.DEWDROP = "晶莹剔透"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEWDROP = "多么美好的事物啊"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DEWDROP = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DEWDROP = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.DEWDROP = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.DEWDROP = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DEWDROP = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DEWDROP = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DEWDROP = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DEWDROP = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DEWDROP = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.DEWDROP = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.DEWDROP = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DEWDROP = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DEWDROP = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.DEWDROP = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.DEWDROP = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.DEWDROP = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 食物buff
-- 安全传送
-- 获得
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = "沙之石的力量!"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.ANNOUNCE_ATTACH_BUFF_SAFETELEPORT = ""
--------------------------------------------------------------------------
-- 失去
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = "沙之石的力量逐渐褪去了"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.ANNOUNCE_DETACH_BUFF_SAFETELEPORT = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 物品
-- 玉露精华
STRINGS.NAMES.ESSENCE = "玉露精华"
STRINGS.RECIPE_DESC.ESSENCE = "逆转食物的时间?"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ESSENCE = "被它影响的食物真的能吃吗…"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ESSENCE = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ESSENCE = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.ESSENCE = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.ESSENCE = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ESSENCE = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ESSENCE = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ESSENCE = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ESSENCE = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ESSENCE = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.ESSENCE = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.ESSENCE = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ESSENCE = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ESSENCE = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.ESSENCE = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.ESSENCE = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.ESSENCE = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 宝石
STRINGS.NAMES.EMERALDGEM = "翠榴宝石"
STRINGS.RECIPE_DESC.EMERALDGEM = "绿油油的宝石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EMERALDGEM = "他闪着...绿色的光?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EMERALDGEM = "能烧吗? 肯定不行"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EMERALDGEM = "漂亮的石头"
STRINGS.CHARACTERS.WENDY.DESCRIBE.EMERALDGEM = "大地的泪水凝结于此"
STRINGS.CHARACTERS.WX78.DESCRIBE.EMERALDGEM = "检测到内部能量"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EMERALDGEM = "看起来像是碱式碳酸铜的颜色"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EMERALDGEM = "我能听到它里面有植物的声音"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EMERALDGEM = "禁锢着生命的活力"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EMERALDGEM = "鲜艳的绿色石头"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EMERALDGEM = "另一种喜欢的绿色!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.EMERALDGEM = "我能用他做很多事"
STRINGS.CHARACTERS.WARLY.DESCRIBE.EMERALDGEM = "安吉丽娜妈妈一定会喜欢"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.EMERALDGEM = "有趣, 他封存了生命的力量"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.EMERALDGEM = "朋友在里面?"
STRINGS.CHARACTERS.WURT.DESCRIBE.EMERALDGEM = "绿色的小石头"
STRINGS.CHARACTERS.WALTER.DESCRIBE.EMERALDGEM = "噢, 它像那个美丽的湖泊"
STRINGS.CHARACTERS.WANDA.DESCRIBE.EMERALDGEM = "让我想起了那个古老的故事"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
STRINGS.NAMES.EMERALDMOONEYE = "翠榴月眼"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EMERALDMOONEYE = "是谁在看着我"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EMERALDMOONEYE = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EMERALDMOONEYE = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.EMERALDMOONEYE = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.EMERALDMOONEYE = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EMERALDMOONEYE = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EMERALDMOONEYE = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EMERALDMOONEYE = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EMERALDMOONEYE = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EMERALDMOONEYE = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.EMERALDMOONEYE = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.EMERALDMOONEYE = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.EMERALDMOONEYE = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.EMERALDMOONEYE = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.EMERALDMOONEYE = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.EMERALDMOONEYE = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.EMERALDMOONEYE = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 法杖
STRINGS.NAMES.EMERALDSTAFF = "翠榴法杖"
STRINGS.RECIPE_DESC.EMERALDSTAFF = "大自然的力量"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EMERALDSTAFF = "用植物制作植物"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EMERALDSTAFF = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EMERALDSTAFF = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.EMERALDSTAFF = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.EMERALDSTAFF = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EMERALDSTAFF = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EMERALDSTAFF = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EMERALDSTAFF = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EMERALDSTAFF = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EMERALDSTAFF = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.EMERALDSTAFF = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.EMERALDSTAFF = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.EMERALDSTAFF = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.EMERALDSTAFF = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.EMERALDSTAFF = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.EMERALDSTAFF = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.EMERALDSTAFF = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 花
STRINGS.NAMES.SUCCULENT_FLOWER_DAWN = "晨露莲花"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FLOWER_DAWN = "好大的一朵花"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_FLOWER_DAWN = ""

-- 勿改 --
local flower={STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_FLOWER_DAWN,STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_FLOWER_DAWN,}
STRINGS.NAMES.SUCCULENT_FLOWER_SUNSET = "夕烧兰花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[1]
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[2]
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[3]
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[4]
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[5]
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[6]
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[7]
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[8]
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[9]
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[10]
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[11]
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[12]
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[13]
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[14]
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[15]
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[16]
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_FLOWER_SUNSET = flower[17]
-- 失去活性的花, 台词无异
STRINGS.NAMES.SUCCULENT_FLOWER_DAWN_B = "晨露莲花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[1]
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[2]
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[3]
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[4]
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[5]
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[6]
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[7]
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[8]
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[9]
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[10]
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[11]
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[12]
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[13]
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[14]
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[15]
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[16]
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_FLOWER_DAWN_B = flower[17]
STRINGS.NAMES.SUCCULENT_FLOWER_SUNSET_B = "夕烧兰花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[1]
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[2]
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[3]
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[4]
STRINGS.CHARACTERS.WX78.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[5]
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[6]
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[7]
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[8]
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[9]
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[10]
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[11]
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[12]
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[13]
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[14]
STRINGS.CHARACTERS.WURT.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[15]
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[16]
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUCCULENT_FLOWER_SUNSET_B = flower[17]
-- end --
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 护符
STRINGS.NAMES.EMERALDAMULET = "翠榴护符"
STRINGS.RECIPE_DESC.EMERALDAMULET = "真好看"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EMERALDAMULET = "大自然藏于心中"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EMERALDAMULET = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EMERALDAMULET = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.EMERALDAMULET = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.EMERALDAMULET = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EMERALDAMULET = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EMERALDAMULET = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EMERALDAMULET = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EMERALDAMULET = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EMERALDAMULET = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.EMERALDAMULET = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.EMERALDAMULET = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.EMERALDAMULET = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.EMERALDAMULET = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.EMERALDAMULET = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.EMERALDAMULET = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.EMERALDAMULET = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 车前蓟
STRINGS.NAMES.THISTLE_BUSH = "车前蓟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THISTLE_BUSH = "噢! 没有刺的仙人掌花丛"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.THISTLE_BUSH = "沙漠里也有会花吗?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.THISTLE_BUSH = "没有尖刺才公平"
STRINGS.CHARACTERS.WENDY.DESCRIBE.THISTLE_BUSH = "失去锋芒的美丽会给它带来毁灭"
STRINGS.CHARACTERS.WX78.DESCRIBE.THISTLE_BUSH = "检测到无威胁性"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.THISTLE_BUSH = "以我的经验来看, 它与多肉同科"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.THISTLE_BUSH = "没有尖刺? 万幸"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.THISTLE_BUSH = "它们还是这么美丽"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.THISTLE_BUSH = "这是赐予沙漠勇士的花冠"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.THISTLE_BUSH = "我们认为这是最好看的部分"
STRINGS.CHARACTERS.WINONA.DESCRIBE.THISTLE_BUSH = "沙漠里开出的花? 我可以碰它吗?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.THISTLE_BUSH = "温和,美丽且可食用"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.THISTLE_BUSH = "它不会扎我, 太棒了"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.THISTLE_BUSH = "漂亮的朋友"
STRINGS.CHARACTERS.WURT.DESCRIBE.THISTLE_BUSH = "以前从没见过这种花, 浮浪噗"
STRINGS.CHARACTERS.WALTER.DESCRIBE.THISTLE_BUSH = "仙人掌花丛, 新发现!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.THISTLE_BUSH = "我的时间和它一样, 所剩无几"
-- 移植的，台词无异
STRINGS.NAMES.THISTLE_KID = "车前蓟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THISTLE_KID = "噢! 没有刺的仙人掌花丛"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.THISTLE_KID = "沙漠里也会有火花吗?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.THISTLE_KID = "没有尖刺才公平"
STRINGS.CHARACTERS.WENDY.DESCRIBE.THISTLE_KID = "失去锋芒的美丽会给它带来毁灭"
STRINGS.CHARACTERS.WX78.DESCRIBE.THISTLE_KID = "检测到无威胁性"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.THISTLE_KID = "以我的经验来看, 它与多肉同科"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.THISTLE_KID = "没有尖刺? 万幸"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.THISTLE_KID = "它们还是这么美丽"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.THISTLE_KID = "这是赐予沙漠勇士的花冠"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.THISTLE_KID = "我们认为这是最好看的部分"
STRINGS.CHARACTERS.WINONA.DESCRIBE.THISTLE_KID = "沙漠里开出的花? 我可以碰它吗?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.THISTLE_KID = "温和, 美丽且可食用"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.THISTLE_KID = "它不会扎我, 太棒了"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.THISTLE_KID = "漂亮的朋友"
STRINGS.CHARACTERS.WURT.DESCRIBE.THISTLE_KID = "以前从没见过这种花, 浮浪噗"
STRINGS.CHARACTERS.WALTER.DESCRIBE.THISTLE_KID = "新发现!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.THISTLE_KID = "我的时间和它一样, 所剩无几"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 种子
STRINGS.NAMES.THISTLE_SEED = "车前蓟种子"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THISTLE_SEED = "包裹着顽强的小生命"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.THISTLE_SEED = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.THISTLE_SEED = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.THISTLE_SEED = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.THISTLE_SEED = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.THISTLE_SEED = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.THISTLE_SEED = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.THISTLE_SEED = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.THISTLE_SEED = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.THISTLE_SEED = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.THISTLE_SEED = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.THISTLE_SEED = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.THISTLE_SEED = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.THISTLE_SEED = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.THISTLE_SEED = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.THISTLE_SEED = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.THISTLE_SEED = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 遗迹
STRINGS.NAMES.TOTEM = "遗迹赝品"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTEM = "虽然是假的,但是能摸得到"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOTEM = "不能打火的石头对于我没有用处"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOTEM = "沃尔夫刚把它举起来了!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOTEM = "随风沙而去或许是它最好的归宿"
STRINGS.CHARACTERS.WX78.DESCRIBE.TOTEM = "无机物的克隆"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOTEM = "它能让我更多了解那个故事"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOTEM = "这是块大磨刀石"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOTEM = "提醒我不要重蹈覆辙"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOTEM = "我就是征服沙漠的战士!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOTEM = "我们把它带回家"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TOTEM = "尽我可能复制了它"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TOTEM = "可以装饰我的厨房"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TOTEM = "其实看上去还不错"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TOTEM = "不错的花盆"
STRINGS.CHARACTERS.WURT.DESCRIBE.TOTEM = "这个更干燥吧...格浪浮"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TOTEM = "我有新的探险故事和大家讲"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TOTEM = "我有比浪费时间在看着它上更重要的事情"
-- 包裹，台词无异
STRINGS.NAMES.TOTEM_ITEM = "遗迹赝品包裹"
STRINGS.RECIPE_DESC.TOTEM_ITEM = "近乎完美的复制品"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTEM_ITEM = "虽然是假的,但是能摸得到"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOTEM_ITEM = "不能打火的石头对于我没有用处"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOTEM_ITEM = "沃尔夫刚把它举起来了!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOTEM_ITEM = "随风沙而去或许是它最好的归宿"
STRINGS.CHARACTERS.WX78.DESCRIBE.TOTEM_ITEM = "无机物的克隆"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOTEM_ITEM = "它能让我更多了解那个故事"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOTEM_ITEM = "这是块大磨刀石"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOTEM_ITEM = "提醒我不要重蹈覆辙"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOTEM_ITEM = "我就是征服沙漠的战士!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOTEM_ITEM = "我们把它带回家"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TOTEM_ITEM = "尽我可能复制了它"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TOTEM_ITEM = "可以装饰我的厨房"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TOTEM_ITEM = "其实看上去还不错"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TOTEM_ITEM = "不错的花盆"
STRINGS.CHARACTERS.WURT.DESCRIBE.TOTEM_ITEM = "这个更干燥吧...格浪浮"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TOTEM_ITEM = "我有新的探险故事和大家讲"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TOTEM_ITEM = "我有比浪费时间在看着它上更重要的事情"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 科技建筑
STRINGS.NAMES.TOTEM_REAL = "遗迹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTEM_REAL = "我好像看到了真的海市蜃楼"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOTEM_REAL = "干燥无趣的石头"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOTEM_REAL = "我想我大概能抬的动他, 或许"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOTEM_REAL = "生命和他没有什么关系, 死亡对它才有意义"
STRINGS.CHARACTERS.WX78.DESCRIBE.TOTEM_REAL = "自然的无聊产物"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOTEM_REAL = "过不了多久, 连这也会消失"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOTEM_REAL = "树在哪呢?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOTEM_REAL = "古代文明的最后遗迹"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOTEM_REAL = "它背后肯定有一个伟大的战士的故事"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOTEM_REAL = "我们觉得它很古老"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TOTEM_REAL = "再精巧的手也做不出这么美丽的物品"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TOTEM_REAL = "又一片绿洲? 还是我眼花了"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TOTEM_REAL = "古代文明? 我可不信"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TOTEM_REAL = "沙漠的朋友喜欢它"
STRINGS.CHARACTERS.WURT.DESCRIBE.TOTEM_REAL = "它太干了...噗浪咯"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TOTEM_REAL = "探险徽章加一!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TOTEM_REAL = "神奇的古代遗物, 属于它的时代已经过去了"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 喷泉
STRINGS.NAMES.PYTHON_FOUNTAIN = "喷泉"
--[[STRINGS.RECIPE_DESC.PYTHON_FOUNTAIN = "一座大喷泉"]]-- 不需要
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PYTHON_FOUNTAIN = "看起来有点眼熟..."
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PYTHON_FOUNTAIN = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PYTHON_FOUNTAIN = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PYTHON_FOUNTAIN = ""

-- 包裹，台词无异
STRINGS.NAMES.PYTHON_FOUNTAIN_ITEM = "喷泉包裹"
STRINGS.RECIPE_DESC.PYTHON_FOUNTAIN_ITEM = "一座大喷泉"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PYTHON_FOUNTAIN_ITEM = "看起来有点眼熟..."
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.PYTHON_FOUNTAIN_ITEM = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 科技栏名字
STRINGS.TABS.OASIS = "沙漠遗迹"
--------------------------------------------------------------------------
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 帐篷
STRINGS.NAMES.TENT_LEAVES = "绿荫帐篷"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENT_LEAVES =
{
    --[[正常检查]]  GENERIC = "舒适的帐篷",
    --[[烧毁]]      BURNT = "可惜",
    --[[燃烧中]]    BURNING = "快灭火!",
}
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.TENT_LEAVES =
{
    GENERIC = "",
    BURNT = "",
    BURNING = "",
}
--------------------------------------------------------------------------
-- 包裹，使用建筑台词
STRINGS.NAMES.TENT_LEAVES_ITEM = "绿荫帐篷"
STRINGS.RECIPE_DESC.TENT_LEAVES_ITEM = "考虑一下把它带走吗"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENT_LEAVES_ITEM = "随身携带的小帐篷"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.TENT_LEAVES_ITEM = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.TENT_LEAVES_ITEM = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.TENT_LEAVES_ITEM = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 晾植物架
STRINGS.NAMES.VEGRACK = "晾植物架"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEGRACK =
{
    --[[晾晒完成]]DONE = "可以收采了",
    --[[正在晾晒]]DRYING = "还要一点时间",
    --[[正在下雨]]DRYINGINRAIN = "这可不是该下雨的时候",
    --[[正常检查]]GENERIC = "可以晾晒植物",
}
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.VEGRACK =
{
    DONE = "",
    DRYING = "",
    DRYINGINRAIN = "",
    GENERIC = "",
}
--------------------------------------------------------------------------
-- 包裹，使用建筑台词
STRINGS.NAMES.VEGRACK_ITEM = "晾植物架包裹"
STRINGS.RECIPE_DESC.VEGRACK_ITEM = "只能晾植物"
STRINGS.NAMES.VEGRACK = "晾植物架"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEGRACK = "可以晾晒植物"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VEGRACK = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VEGRACK = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.VEGRACK = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.VEGRACK = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VEGRACK = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VEGRACK = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VEGRACK = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VEGRACK = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VEGRACK = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.VEGRACK = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.VEGRACK = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VEGRACK = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VEGRACK = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.VEGRACK = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.VEGRACK = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.VEGRACK = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
-- 妙脆角
STRINGS.NAMES.VEGGIE_CRISPS = "果蔬妙脆角"
-- 通用(威尔逊)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEGGIE_CRISPS = "非油炸, 无添加, 零负担"
-- 薇洛
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃尔夫冈
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VEGGIE_CRISPS = ""
-- 温蒂
STRINGS.CHARACTERS.WENDY.DESCRIBE.VEGGIE_CRISPS = ""
-- WX78
STRINGS.CHARACTERS.WX78.DESCRIBE.VEGGIE_CRISPS = ""
-- 维克巴顿
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VEGGIE_CRISPS = ""
-- 伍迪
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VEGGIE_CRISPS = ""
-- 麦斯威尔
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VEGGIE_CRISPS = ""
-- 薇格弗德
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VEGGIE_CRISPS = ""
-- 韦伯
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VEGGIE_CRISPS = ""
-- 维诺娜
STRINGS.CHARACTERS.WINONA.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃利
STRINGS.CHARACTERS.WARLY.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃拓克斯
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃姆伍德
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃特
STRINGS.CHARACTERS.WURT.DESCRIBE.VEGGIE_CRISPS = ""
-- 沃尔特
STRINGS.CHARACTERS.WALTER.DESCRIBE.VEGGIE_CRISPS = ""
-- 旺达
STRINGS.CHARACTERS.WANDA.DESCRIBE.VEGGIE_CRISPS = ""
--------------------------------------------------------------------------
--------------------------------------------------------------------------
--------------------------------------------------------------------------
--------------------------------------------------------------------------








-- 动作，取消
-- STRINGS.HARVEST_CRISP = "收采"
-- STRINGS.CRISP = "晾干"

--[[
-- 惠特妮
STRINGS.TABS.WHITNEY_TAB = "绿洲建筑"

-- 皮肤
STRINGS.SKIN_NAMES.MEDPOT_SPA = "小虹玉"
STRINGS.SKIN_DESCRIPTIONS.MEDPOT_SPA = "小虹玉"

STRINGS.SKIN_NAMES.LARGEPOT_FORMA = "新生"
STRINGS.SKIN_DESCRIPTIONS.LARGEPOT_FORMA = "新生"
STRINGS.SKIN_NAMES.LARGEPOT_FORMB = "舒展"
STRINGS.SKIN_DESCRIPTIONS.LARGEPOT_FORMB = "舒展"
STRINGS.SKIN_NAMES.LARGEPOT_FORMC = "成熟"
STRINGS.SKIN_DESCRIPTIONS.LARGEPOT_FORMC = "成熟"
]]


--[[
STRINGS.NAMES.ABCDEFG = ""
STRINGS.RECIPE_DESC.ABCDEFG = ""
STRINGS.UI.COOKBOOK.ABCDEFG = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WENDY.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WX78.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WINONA.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WARLY.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WURT.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WALTER.DESCRIBE.ABCDEFG = ""
STRINGS.CHARACTERS.WANDA.DESCRIBE.ABCDEFG = ""
]]
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE.PPF_SUCCULENTJELLY = "耐高温的原料"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PPF_SUCCULENTJELLY = "这些植物并没有可食用的记载"
-- STRINGS.CHARACTERS.WEBBER.DESCRIBE.PPF_SUCCULENTJELLY = "植物不合我们的胃口"
